### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by Havouza** [thirtybees/sitemap#1]
Used the updated sitemap module today. Created sitemap and added the url to the webtools.
Result see screenshot. Look at the link when I point at the sitemap link. No wonder it cant be found or...
![screenshot 2017-06-17 13 32 18](https://user-images.githubusercontent.com/25871096/27252364-4a03a98a-5365-11e7-8153-fcecf2ccb01f.png)

**Comment by Dh42** [comment]
This is not an issue with the module. In GWT they automatically add the site url. You need to strip that from what you add. Other services do not add it, so its best to keep the whole url I would think.
