### ISSUE TITLE
Sitemap Module - Friendly URL

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/sitemap#10]
On TB, we don't have a friendly URL:
![image](https://github.com/thirtybees/thirtybees/assets/38436949/27617d3a-e65c-40c3-9ac7-9750f1c0230c)

We installed the Sitemap Module, and we got the https://test.com/1_index_sitemap.xml

The 1_index_sitemap.xml was generated with friendly URL.

That way, the search engines (Google, …) have the friend URL, but on the site, we have no friendly URL and the search return:

![image](https://github.com/thirtybees/thirtybees/assets/38436949/b967a3ab-f9db-4294-8b4e-11466029857d)

We suppose the Sitemap Module should generate 1_index_sitemap.xml, the accord with the:
![image](https://github.com/thirtybees/thirtybees/assets/38436949/eb59ec38-ee8d-4bc2-960d-ac5726afce92)

**Comment by getdatakick** [comment]
I don't understand. 

This module generates xml file in root of your installation:

https://github.com/thirtybees/sitemap/blob/c1ade8ced29c953c5dd2e19d992cbcf437628066/sitemap.php#L540

There is no friendly urls involved at all.

Please explain better.

**Comment by Jorgemgm** [comment]
I have:
Preferences => SEO&URLs => SET UP URLS => Friendly URL: No

But the URLs on sitemap.xml comes unexpectedly with FriendlyUrl instead of No Friendly URL.

Maybe it's a wrong configuration, but I don't know where.

**Comment by getdatakick** [comment]
I can't reproduce this, this works properly on latest thirty bees 1.5.0 and latest version of the module.

1) I've disabled friendly url and re-generated sitemap file. Url uses non-friendly schema with index.php:
![image](https://github.com/thirtybees/sitemap/assets/34651851/1601fdfc-a8ce-450d-a40a-476b78f30184)

2) I've enabled friendly url, and once again regenerate sitemap file. Urls use friendly urls.
![image](https://github.com/thirtybees/sitemap/assets/34651851/d9965999-8085-4c5a-8bbb-2154b83be006)

Everything works as expected. Maybe you didn't regenerate the sitemap files? Or you have some overrides, or are using old thirty bees, or old version of module.

**Comment by Jorgemgm** [comment]
Thanks for the module.

The Edition that we started on the ThirtyBees was 1.0.4 but always updated the TB, and now it's 1.4.0, and all modules are updated.

We have: Preferences => SEO&URLs => SET UP URLS => Friendly URL: No
![image](https://github.com/thirtybees/sitemap/assets/38436949/f96b037b-6bc4-4b08-96b2-f6ed597c856e)

Yes, the TB always regenerates the sitemap file.
![image](https://github.com/thirtybees/sitemap/assets/38436949/d806dd52-fd8b-4175-a291-4fde9f9fff04)

The issue is not on 1_index_sitemap.xml but it is on 1_en_0_sitemap.xml

Always the http://XXXXXXXXX/1_en_0_sitemap.xml is created with friendly URLs
![image](https://github.com/thirtybees/sitemap/assets/38436949/d7e40376-d522-4902-a30b-d95d031cf6d2)

Because we have Friendly URL: No and the 1_en_0_sitemap.xml it’s created with Friendly URL: Yes, we can’t find that friendly URL page:
![image](https://github.com/thirtybees/sitemap/assets/38436949/d91ef1b5-e5b9-4ed4-a47b-43b0a07147fa)

I supposed the 1_en_0_sitemap.xml could return URLs:
- FriendlyUrl (when we have Friendly URL: Yes), or 
- No Friendly URL (when we have Friendly URL: No).

**Comment by getdatakick** [comment]
I can't reproduce this on vanilla installation of thirty bees 1.4.0 or bleeding edge, latest version of module.

I expect you have some sort of core modification, or override, that is causing this problem.
