### ISSUE TITLE
Module only updates default shop's sitemap with cronjob.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/sitemap#14]
thirtybees: edge as of yesterday

Multishop: yes

Module version: latest as of today

Issue: when setting up multishop scenario the sitemap module only updates the default (ID=1) shop sitemap when called from a cronjob.

![image](https://github.com/thirtybees/sitemap/assets/11251370/0f047484-59f0-4b87-94b6-38234f6bee3a)

Repo steps: multishop installation with 2 or more shops. Set up cronjobs using the supplied links in the module. Only the shop id=1 sitemap is updated despite the links contain different ids at the end. If you set up the jobs to run simultaneously the first sitemap is regenerated X times at the same time and shows different rows in the module page when ready. If set in different time the row is overwritten. Non-default shops sitemap's are not regenerated.

Cronjobs are set as follows:

wget https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=1
wget https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=2
wget https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=3
wget https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=4
etc...

Other: regeneration works properly by using the button 'Generate sitemap'. Tried using the appropriate domain for each shop ID - no effect.

**Comment by getdatakick** [comment]
Can't reproduce this behaviour.
Multistore support was fixed recently in commit a08e27392c6da81fcbdbb99ca520678e30b92403, so maybe you are using old version of module?

**Comment by therampagerado** [comment]
Thanks to datakick the answer is: one has to add "" around the cronjob URL if it contains & otherwise the URL is truncated.

The correct cronjob is:

wget "https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=1"
wget "https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=2"
wget "https://www.domain.com/modules/sitemap/sitemap-cron.php?token=TOKEN&id_shop=3"
etc.
