### ISSUE TITLE
Sitemap not indexing Beesblog

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/sitemap#3]
Hi Guys,

seems that the sitemap module is not indexing the blog module at all, is there an option somewhere I should be activating?

**Comment by firstred** [comment]
I do not see a `hookModuleRoutes` in the beesblog module. Can you close
this issue and report it in the blog repository? I think the functionality
needs to be added to the blog module.

**Comment by selwynorren** [comment]
Okay great thanks, I did find this on line 148. Is it not the same thing?
            || !$this->registerHook('moduleRoutes')

**Comment by firstred** [comment]
Oh it does. I apparently just had wrong search settings in my IDE, I guess.

The code looks good to me. Can you check if it actually is hooked to `hookModuleRoutes` in your store?

**Comment by firstred** [comment]
Let's continue here: https://github.com/thirtybees/beesblog/issues/14
