### ISSUE TITLE
Creating a non existant Sitemap entry

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/sitemap#5]
Hi Site map keeps creates strange URL's

I have two cases here. First the home url is not used anywhere, however this entry keeps being created:
<url><loc>https://www.orren-life.com/home</loc><priority>0.8</priority><lastmod>2017-10-12T23:54:54+02:00</lastmod><changefreq>weekly</changefreq></url>

This constantly produces a 404 error.

Secondly I get the following entry at least 6 times (repeated and not sequentially)
<url><loc>https://www.orren-life.com/</loc><priority>1.0</priority><changefreq>weekly</changefreq></url>

**Comment by selwynorren** [comment]
Hi Guys, just want to bump this issue. I am having major headaches with sitemap generation and Google webmaster tools. There is major issues for me when trying to generate sitemap files for the blog as well.

**Comment by pauld-codes** [comment]
Should be resolved with this pull request: #6

**Comment by selwynorren** [comment]
Howdy, yup that does indeed fix the issue up for me. However I noticed something very alarming. I just recently ran the updater to 1.07, everything went smoothly, however when I compared the sitemap.php with the one here on Github, there were roughly 10 lines less on my version. This means the modules are not updating right?

**Comment by pauld-codes** [comment]
Someone need to merge pull request.

**Comment by Dh42** [comment]
Fixed with this pull request, https://github.com/thirtybees/sitemap/pull/6 New release build and set.
